### ISSUE TITLE
Question about the evaluation 

### ISSUE THREAD

**Issue by yhcc** [SapienzaNLP/gsrl#2]
Thanks for publishing your code. When I reading the code for the evaluation, I have a question concerning the generation of the prediction file.
In https://github.com/SapienzaNLP/gsrl/blob/64291a79c79c212cc5fb025cf5fa33de74445e44/src/modelling/evaluation.py#L81
, if the input sentence is [A, B, C, D, E, F, G], and we assume the golden predicate is [A, C, F] (the role is B, D, G, we assume each predicate has only one role), and the model predicts the predicate is [A, F] (and the corresponding role is B, G, respectively). Based on the code, the results will be something like 
```
A	(V*)	*
-	Arg0*)	*	
C	*	(V*)	*
-	*	*
-	*	*
F	*	(V*)	
-	*	(Arg0*)
```
namely, that some columns will have two predicates, and some rows will have more columns (the third column has three rows, while others have two). Will this code generate this way? If so, will this negatively influence the performance?

**Comment by rexhinab** [comment]
Hello, 

Thank you for your interest in our work!
Could you please clarify if this is your assumption by looking at the code or this is the actual result? In fact, I believe this should not be the case even because the evaluation script would not work. 
The idea behind it is that we fill each position with the maximum cases it can have a role, in this case, 3, and then fill in the roles to the proper positions, e.g., if a token plays a role in the first predicate, the first column is filled and so on. 
Let me know if this is clear and makes sense to you :)
